name: For each Kernel PR
on:
  pull_request:
    paths:
    - kernel/**
    - "!kernel/README.md"
jobs:
  kconfig-validation:
    runs-on: ubuntu-20.04
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver-opts: network=host

    - name: Build and push kconfig
      uses: docker/build-push-action@v2
      with:
        context: ./kernel/
        platforms: linux/amd64,linux/arm64
        file: ./kernel/Dockerfile.kconfig
        push: true
        tags: localhost:5000/tinkerbell/kconfig:latest
        build-args: |
          KERNEL_VERSIONS=5.10.11
  kernel-validation:
    runs-on: self-hosted
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - run: echo "REGISTRY=$(ip addr show dev bond0 | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }' | head -n 1)" >> $GITHUB_ENV

    - run: make -C kernel build ORG=${REGISTRY}:5000

    # TODO: add artifacts for the built images
    #- uses: actions/upload-artifact@v2
    #  with:
    #    name: TODO
    #    path: TODO
