name: For each Kernel PR
on:
  pull_request:
    paths:
      - kernel/**
      - "!kernel/README.md"
jobs:
  kernel-validation:
    runs-on: self-hosted
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use docker buildx
        run: docker buildx create --use

      - run: echo "REGISTRY=$(ip addr show dev bond0 | awk '$1 == "inet" { sub("/.*", "", $2); print $2 }' | head -n 1)" >> $GITHUB_ENV

      - run: make -C kernel devbuild ORG=${REGISTRY}:5000

    # TODO: add artifacts for the built images
    #- uses: actions/upload-artifact@v3
    #  with:
    #    name: TODO
    #    path: TODO
